#eureka:
 # client:
   # serviceUrl:
    #  defaultZone: http://localhost:8761/eureka/
spring:
  #配置服务追踪
  #zipkin:
   # base-url: http://localhost:9411
  application:
    name: spring-boot-study
  #配置mybatis-yml文件生效
  profiles:
    active: mybatis
  #配置阿里巴巴连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring-boot?characterEncoding=utf8
    username: yangyiwei
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  #配置mongodb
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/spring-boot
  #配置redis
  redis:
    database: 0
    host: 192.168.9.128
    port: 6379
    timeout: 0
    password: 123456
    pool:
      #最大连接数
      max-active: 8 
      #阻塞时间
      max-wait: -1 
      #最大空闲
      max-idle: 8 
      #最小空闲
      min-idle: 0 
  #配置热部署工具   
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: templates/**
  #配置thymeleaf
  thymeleaf:
    cache: false
  #配置activeMQ
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    in-memory: true
    pool:
      enabled: false
 # output:
   # ansi:
     # enabled: ALWAYS
#配置日志
logging:
  path: /com/yangyiwei
  level:
    com.weige.ssm: debug     
